version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - /data/docker-data/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      - SPRING_DATA_REDIS_HOST=redis
      - LOGSTASH_HOST=logstash
    external_links:
      - mysql:db
      - nacos-registry:nacos-registry
  mall-search:
    image: mall/mall-search:1.0-SNAPSHOT
    container_name: mall-search
    ports:
      - 8081:8081
    volumes:
      - /data/docker-data/app/mall-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
    external_links:
      - elasticsearch:es
      - mysql:db
      - nacos-registry:nacos-registry
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - /data/docker-data/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    external_links:
      - redis:redis
      - mongo:mongo
      - mysql:db
      - rabbitmq:rabbit
      - nacos-registry:nacos-registry
  mall-auth:
    image: mall/mall-auth:1.0-SNAPSHOT
    container_name: mall-auth
    ports:
      - 8401:8401
    volumes:
      - /data/docker-data/app/mall-auth/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-gateway:
    image: mall/mall-gateway:1.0-SNAPSHOT
    container_name: mall-gateway
    ports:
      - 8201:8201
    volumes:
      - /data/docker-data/app/mall-gateway/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-monitor:
    image: mall/mall-monitor:1.0-SNAPSHOT
    container_name: mall-monitor
    ports:
      - 8101:8101
    volumes:
      - /data/docker-data/app/mall-monitor/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-ai:
    image: mall/mall-ai:1.0-SNAPSHOT
    container_name: mall-ai
    ports:
      - 8002:8002
    volumes:
      - /data/docker-data/app/mall-ai/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - SPRING_PROFILES_ACTIVE=prod
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    external_links:
      - mysql:db
      - redis:redis
      - nacos-registry:nacos-registry
      - mall-search:mall-search
