spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-registry:8848
      config:
        server-addr: nacos-registry:8848
        file-extension: yaml
  config:
    import:
      - optional:nacos:mall-ai-prod.yaml
  data:
    redis:
      host: redis
  datasource:
    url: jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.macro.mall.ai.model
  configuration:
    map-underscore-to-camel-case: true

mall-ai:
  integration:
    mall-search:
      base-url: http://mall-search:8081
    mall-admin:
      base-url: http://mall-admin:8080
